terraform-google-modules/terraform-google-network

README.md, examples/multi_vpc/main.tf, examples/multi_vpc/outputs.tf, examples/simple_project/main.tf, examples/simple_project/outputs.tf, examples/simple_project/variables.tf, main.tf, outputs.tf
Added enable VPC flow logs option to module and examples
=> Add vpc flow logs option to subnets

README.md, examples/multi_vpc/README.md, examples/multi_vpc/outputs.tf, examples/simple_project/README.md, examples/simple_project/outputs.tf, outputs.tf, test/integration/gcloud-test/templates/outputs.tf.tmpl
This change adds the `self_link` of the created network as an output. Also updated the examples and generated the READMEs with terraform-docs.
=> Add the created network URI as an output

README.md
Overview:
- The enable_flow_logs field to subnetwork resource was introduced in terraform-provider-google version 1.12.0. Used at https://github.com/rbramwell/terraform-google-network/blob/master/main.tf#L37
- See https://github.com/terraform-providers/terraform-provider-google/blob/master/CHANGELOG.md#1120-may-04-2018
=> Updated terraform-provider-google min version to 1.12.0

main.tf, outputs.tf
This will fix #5, which causes errors when the `secondary_ranges` map does not define any secondary ranges.  This keeps the `subnets_secondary_ranges` output, but we might consider removing it altogether, since it is capable of producing such useless output as:
```
Outputs:
secondary_ranges = [
[
],
[
],
[
]
]
```
Removing the output is something I'm happy to do, if that's the direction we choose to go.
=> Adds subnet data source, allows no secondary range in subnets; fixes #5

README.md, outputs.tf
We ran into this when using the `google_compute_router_nat`
tf module. This requires the subnet self links as inputs when
defining the NAT on a per subnet basis
=> Add subnet_self_links as outputs

.kitchen.yml, README.md, examples/delete_default_gateway_routes/README.md, examples/delete_default_gateway_routes/main.tf, examples/delete_default_gateway_routes/outputs.tf, examples/delete_default_gateway_routes/variables.tf, examples/multi_vpc/README.md, main.tf, scripts/delete-default-gateway-routes.sh, test/fixtures/delete_default_gateway_routes/main.tf, test/fixtures/delete_default_gateway_routes/outputs.tf, test/fixtures/delete_default_gateway_routes/route.tf, test/fixtures/delete_default_gateway_routes/variables.tf, test/integration/delete_default_gateway_routes/controls/gcloud.rb, test/integration/delete_default_gateway_routes/inspec.yml, variables.tf
This commit introduces the ability to delete the default gateway route
that is created for the VPC network (issue #25). If the input variable
`var.delete_default_internet_gateway_routes` is set then a null_resource
uses the local-exec provisioner to execute a script that filters for all
network routes within the `project_id` whose name begins with
"default-route" and who contains a next hop of "default-internet-gateway"
and then deletes them. This functionality is useful in the event that
all egress traffic should be routed through a single device instead of
directly to the default internet gateway.  Without this change there is
no way to automate the deletion of those routes.
=> Provide ability to delete default gateway route

main.tf
SVPC creation needs to depend on VPC Configuration to complete to prevent race scenario.
=> SVPC depends on VPC Config

.kitchen.yml, CHANGELOG.md, examples/submodule_firewall/README.md, examples/submodule_firewall/main.tf, examples/submodule_firewall/outputs.tf, examples/submodule_firewall/variables.tf, helpers/combine_docfiles.py, modules/fabric-net-firewall/README.md, modules/fabric-net-firewall/main.tf, modules/fabric-net-firewall/outputs.tf, modules/fabric-net-firewall/variables.tf, test/fixtures/submodule_firewall/main.tf, test/fixtures/submodule_firewall/outputs.tf, test/fixtures/submodule_firewall/terraform.tfvars, test/fixtures/submodule_firewall/variables.tf, test/integration/simple_project/inspec.yml, test/integration/simple_project_with_regional_network/inspec.yml, test/integration/submodule_firewall/controls/gcloud.rb, test/integration/submodule_firewall/controls/gcp.rb, test/integration/submodule_firewall/inspec.yml
This brings in the net-firewall module as a submodule.
I added a new example and tests, as I was not too sure that adding the submodule to the simple example was fine.
I'm not too sure about the version bump in `inspec.yml`, but it's the only way I could run verify witout Kitchen complaining about a version mismatch.
This PR also contains a minimal fix to the combine docfiles script, so it doesn't fail when a match is not found (as happens in this repo).
=> Initial import of net-firewall submodule from internal version.

README.md, examples/submodule_svpc_access/README.md, examples/submodule_svpc_access/main.tf, examples/submodule_svpc_access/outputs.tf, examples/submodule_svpc_access/variables.tf, modules/fabric-net-svpc-access/README.md, modules/fabric-net-svpc-access/main.tf, modules/fabric-net-svpc-access/outputs.tf, modules/fabric-net-svpc-access/variables.tf, outputs.tf
As per the discussion in #42 this adds a simple submodule to configure Shared VPC network attachments, and the corresponding examples.
The module allows configuring VPC-level access through the `google_compute_shared_vpc_service_project` resource for 0-n projects, or subnet-level access for IAM-style members through the `google_compute_subnetwork_iam_binding` resource.
As discussed, there's a new output in the top-level module to expose the Shared VPC project id, which is used to trigger the inter-module dependency. Contrary to what I expected it seems to work, but even if it didn't it would not cause any major issue, as once SVPC has been turned on and applied, the submodule would work (meaning at most two consecutive apply runs).
There are no tests, as they would need extra service …
=> Second take at Shared VPC configuration.

README.md
Per https://github.com/terraform-google-modules/terraform-google-network/pull/47#discussion_r300796223
We should probably add a note like this to each module's 0.12 upgrade PR.
=> Add a note about 0.11.x compatible version to README

README.md, main.tf
This allows subnets to optionally be created with a description.
For example:
```
subnets = [
{
subnet_name           = "subnet-01"
subnet_ip             = "10.10.10.0/24"
subnet_region         = "us-west1"
},
{
subnet_name           = "subnet-02"
subnet_ip             = "10.10.20.0/24"
subnet_region         = "us-west1"
subnet_private_access = "true"
subnet_flow_logs      = "true"
description           = "This subnet has a description"
},
```
=> feat: adding optional description field to created subnets

main.tf
=> Add depends_on to created_subnets data fetch

modules/fabric-net-firewall/.gitignore, modules/fabric-net-firewall/README.md, modules/fabric-net-firewall/main.tf, modules/fabric-net-firewall/outputs.tf, modules/fabric-net-firewall/variables.tf
Aleks, this is a first shot at adding dynamic rule definitions to the firewall submodule, to make it a bit more flexible.
What I tried to implement here:
- enforcing structure for the rule definitions variable
- combine ingress and egress into a single variable/resource so that the module has few duplications
- correctly handle the incompatibility of tags/service accounts based source and targets
I did some minimal testing and it seems to work. This is an example variable for an ingress rule using both source and target tags, and a source range:
```
dynamic_rules = {
dummy = {
description          = "Dummy rule."
direction            = "INGRESS"
action               = "allow"
ranges               = ["192.168.0.0"]
sources              = ["spam-tag"]
targets              = ["foo-tag", …
```
=> Add dynamic rules to Fabric firewall submodule

Makefile, README.md, main.tf, outputs.tf, variables.tf
This is a no-impact (by default) change which allows network_creation to be separated from subnet and route creation.  Fixes https://github.com/terraform-google-modules/terraform-google-network/issues/88
Tests are still running locally, but it looks like everything is passing until I run out of network quota, so I'm sending the PR to see if it passes CI.
=> Make network creation optional in root module

CHANGELOG.md, Makefile, README.md, build/int.cloudbuild.yaml, build/lint.cloudbuild.yaml, main.tf, outputs.tf, variables.tf
This branch changes outputs to depend on resource attributes when possible, allowing a dependency to be made to the underlying resources.
=> Fix values of outputs

README.md, examples/delete_default_gateway_routes/main.tf, examples/multi_vpc/main.tf, examples/secondary_ranges/main.tf, examples/simple_project/main.tf, examples/simple_project_with_regional_network/main.tf, examples/submodule_firewall/main.tf, main.tf, test/integration/simple_project/controls/gcloud.rb, test/integration/simple_project/controls/gcp.rb
When using this module with the latest Google provider, I noticed a warning about the deprecation of the `enable_flow_logs` setting in the `google_compute_subnetwork`. This was raised #105.  
This PR uses a dynamic block to define the `log_config` of a subnetwork if any of:
- `subnet_flow_logs_interval`
- `subnet_flow_logs_sampling`
- `subnet_flow_logs_metadata`  
are set. Or `subnet_flow_logs`is true.
=> Removing deprecated `enable_flow_logs` setting in favour of log_config

docs/upgrading_to_v2.0.md, helpers/migrate.py
=> 2.0 release upgrade guide

modules/fabric-net-svpc-access/README.md
There's a mistake in the usage example because `host_subnet_users` is a map not an array !
=> Fix fabric-net-svpc-access module usage

README.md, outputs.tf
which is a map with keys `"${subnet_region}/${subnet_name}"` and values being the outputs
of the `google_compute_subnetwork` resource
with this output other modules can obtain data such as `self_link` for particular
subnets without running into resource recreation problems etc. when the number/order
of the subnets changes
=> add subnets output

modules/vpc/outputs.tf
Getting the following error when trying to access the output variable "project_id" of the vpc module
```
Error: Invalid expanding argument value
on .terraform/modules/apps-projects.vpc/modules/vpc/outputs.tf line 33, in output "project_id":
33:   value       = var.shared_vpc_host ? coalesce(google_compute_shared_vpc_host_project.shared_vpc_host.*.project...) : google_compute_network.network.project
The expanding argument (indicated by ...) must be of a tuple, list, or set type.
```
Seems related to a known issue with newest versions of terraform:
https://github.com/hashicorp/terraform/issues/22404
https://github.com/hashicorp/terraform/issues/22576
Can reproduce the issue with this little snippet:
```
variable "enabled" {
default = true
}
resource "random_string" "rnd" {
count   = …
```
=> fix the "Invalid expanding argument value" issue with the newer tfs

modules/fabric-net-svpc-access/README.md, modules/fabric-net-svpc-access/variables.tf
Quoted type constraints are deprecated.
```
Warning: Quoted type constraints are deprecated
on .terraform/modules/-.network_fabric-net-svpc-access/terraform-google-modules-terraform-google-network-270efc6/modules/fabric-net-svpc-access/variables.tf line 30, in variable "service_project_ids":
30:   type        = "list"
Terraform 0.11 and earlier required type constraints to be given in quotes,
but that form is now deprecated and will be removed in a future version of
Terraform. To silence this warning, remove the quotes around "list" and write
list(string) instead to explicitly indicate that the list elements are
strings.
```
=> fix: service_project_ids type

modules/fabric-net-firewall/main.tf
There is a commented line over the enable logging, just removing the comment and allowing the variable to be used.
=> Remove the code comment to use enable_logging

modules/fabric-net-svpc-access/README.md, modules/fabric-net-svpc-access/variables.tf
It's a good practice and terragrunt does not work properly without it.
=> Add variables type as first parameter on all variables

README.md, outputs.tf
Currently there is no way to get the network ID. Add the entire network as an output so users can use it however they need.
=> add network output

helpers/migrate.py
When running the migrate script, it encountered a KeyError `attributes` not found. I looked at the `terraform state pull` output, and saw there was an `attributes_flat` that likely changed in newer Terraform versions. I'm supplying this change to reflect that API change.
=> helpers: Change attributes to attributes_flat

modules/vpc/outputs.tf
Checks that google_compute_shared_vpc_host_project.shared_vpc_host
is not empty before attempting to return the value. Avoids the error
"google_compute_shared_vpc_host_project.shared_vpc_host is empty tuple
The given key does not identify an element in this collection value."
Fixes #176 
This error seems to be caused by terraform deleting the google_compute_shared_vpc_host_project.shared_vpc_host object, but then the outputs being triggered attempts to return an empty value since that object no longer exists. This fix adds a check that the shared_vpc_host values must be true and the google_compute_shared_vpc_host_project.shared_vpc_host value can not be empty for it to return the value stored.
=> Resolve Invalid index error on shared vpc destroy

modules/fabric-net-firewall/README.md, modules/fabric-net-firewall/main.tf, modules/fabric-net-firewall/variables.tf
This PR adds the ability to specify the target_tags attribute for the default firewalls, rather than having them hardcoded within the code
=> Allow to pass target_tags to the default firewalls

.kitchen.yml, Makefile, build/int.cloudbuild.yaml, examples/delete_default_gateway_routes/versions.tf, examples/ilb_routing/versions.tf, examples/multi_vpc/versions.tf, examples/secondary_ranges/versions.tf, examples/simple_project/versions.tf, examples/simple_project_with_regional_network/versions.tf, examples/submodule_firewall/versions.tf, examples/submodule_network_peering/versions.tf, examples/submodule_svpc_access/versions.tf, modules/fabric-net-firewall/versions.tf, modules/fabric-net-svpc-access/versions.tf, modules/network-peering/versions.tf, modules/routes-beta/versions.tf, modules/routes/versions.tf, modules/subnets-beta/versions.tf, modules/subnets/versions.tf, modules/vpc/versions.tf, test/setup/versions.tf, versions.tf
fixes #196 
- relax version constraint to allow usage with 0.13
- Kitchen tests [run with `v0.13.0-rc1`](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/commit/88017ad3bc0d40473ac3d94546660328aeee878d) 
- All tests passed
- module `for_each` spot checked, have not tested `depends_on`, but based on other modules I expect it to work
=> chore: relax tf version to allow 0.13 

modules/subnets-beta/main.tf
This PR is setting default values for the Flow log config block the same way like it's set in the [`subnets`](https://github.com/terraform-google-modules/terraform-google-network/tree/master/modules/subnets/main.tf#L36-L38) sub-module. The reason for this to be set is that if the `subnet_flow_logs` is set to `true`, one of the three attributes must be set otherwise it fails with this error:
```
Error: AtLeastOne
on .terraform/modules/vpc.subnets/modules/subnets-beta/main.tf line 28, in resource "google_compute_subnetwork" "subnetwork":
28: resource "google_compute_subnetwork" "subnetwork" {
"log_config.0.filter_expr": one of
`log_config.0.aggregation_interval,log_config.0.filter_expr,log_config.0.flow_sampling,log_config.0.metadata`
must be specified
```
=> Setting default values for Flow log config

README.md, examples/delete_default_gateway_routes/main.tf, examples/ilb_routing/main.tf, examples/multi_vpc/main.tf, examples/secondary_ranges/main.tf, examples/simple_project/main.tf, examples/simple_project_with_regional_network/main.tf, examples/submodule_firewall/main.tf, examples/submodule_network_peering/main.tf, examples/submodule_svpc_access/main.tf, main.tf, modules/vpc/README.md, modules/vpc/main.tf, modules/vpc/variables.tf, modules/vpc/versions.tf, test/integration/simple_project/controls/gcloud.rb, variables.tf
This is a potential update to address feature request #220. It adds an `mtu` variable to root and vpc modules that will set MTU on `google_compute_network` resource.
The update has been tested in a few non-production VPCs without any problems yet.
*Note:* MTU suport has a dependency on release [3.45.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v3.45.0) of google provider.
=> Support custom MTU on VPCs

README.md, modules/vpc/README.md, modules/vpc/variables.tf, variables.tf
Recent changes to this module added the MTU parameter which defaults to value `1460`. Unfortunately that breaks the backward compatibility (from the time when the MTU parameter wasn't present) and it forces the network to be rebuilt unless the MTU is set to `0`. From the API point of view this is not necessary as the parameter is [optional](https://github.com/hashicorp/terraform-provider-google/blob/master/google/resource_compute_network.go#L81). Basically, if the MTU is not set, it defaults to 1460 anyway so it's not necessary set it.
=> Set default value of MTU to 0

modules/fabric-net-firewall/main.tf
This PR is renaming attribute `enable_logging` to `log_config` in order to prevent the following warning:
```
Warning: Attribute is deprecated
on .terraform/modules/vpc.peering_fw_dev_mgmt/modules/fabric-net-firewall/main.tf line 134, in resource "google_compute_firewall" "custom":
134:   enable_logging          = lookup(each.value.extra_attributes, "enable_logging", null)
Deprecated in favor of log_config
```
=> Renaming deprecated attribute

modules/firewall-rules/versions.tf
Remove terraform version constrain on a newly introduced module
=> Support terraform 0.14 on firewall-rules modules

modules/routes-beta/main.tf
`next_hop_gateway` cannot be passed (even as "") if `next_hop_ilb` is set:
```
Error: ExactlyOne
on .terraform/modules/base_transitivity.routes/modules/routes-beta/main.tf line 36, in resource "google_compute_route" "route":
36:   next_hop_ilb           = lookup(var.routes[count.index], "next_hop_ilb", null)
"next_hop_ilb": only one of
`next_hop_gateway,next_hop_ilb,next_hop_instance,next_hop_ip,next_hop_vpn_tunnel`
can be specified, but `next_hop_gateway,next_hop_ilb` were specified.
```
=> fix non-internet routes

modules/firewall-rules/versions.tf
=> fix: Update required Terraform version for firewall-rules submodule

modules/firewall-rules/main.tf
This PR eliminates the following syntax deprecation warning:
```
Warning: Interpolation-only expressions are deprecated
on .terraform/modules/network/terraform-google-network-3.1.1/modules/firewall-rules/main.tf line 18, in resource "google_compute_firewall" "rules":
18:   for_each                = { for r in var.rules : "${r.name}" => r }
Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.
Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of …
```
=> Eliminate deprecation warning due to pre-0.12 string interpolation syntax

modules/firewall-rules/versions.tf, modules/network-peering/README.md, modules/network-peering/main.tf, modules/network-peering/variables.tf
This introduces support for the export_subnet_routes_with_public_ip and import_subnet_routes_with_public_ip variables in the google_compute_network_peering resources. This is necessary when peering VPCs that are using Privately Used Public IPs (PUPIs) as the private subnet IPs.
Note - the defaults proposed in this PR are false for both variables, but the provider's default for [export_subnet_routes_with_public_ip](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_network_peering#export_subnet_routes_with_public_ip) is true (the import variable is also set to false, by default, here); because these come in pairs (defining each end of the peering), and because the current Network Peering submodule doesn't override these defaults, it will cause each …
=> Addresses Issue #248 (Add Support for Exporting PUPIs - Network Peering Module)

modules/fabric-net-firewall/README.md, modules/fabric-net-firewall/variables.tf
I get below error
```
Error: Incorrect attribute value type
on main.tf line 91, in resource "google_compute_firewall" "allow-tag-http":
91:   target_tags   = var.http_target_tags
|----------------
| var.http_target_tags is "[\"http\"]"
Inappropriate value for attribute "target_tags": set of string required.
```
Could you check this PR to fix the error? Thanks
=> Add variable type for http_target_tags variable

examples/basic_shared_vpc/README.md, examples/basic_shared_vpc/main.tf
Added snippet that creates a VM with the reserved IP address
This allows us to have a Terraform that more closely matches the other tabs in the https://cloud.devsite.corp.google.com/vpc/docs/provisioning-shared-vpc#creating_an_instance_in_a_shared_subnet section
=> Added snippet that creates a VM with the reserved IP address

examples/network_service_tiers/README.md, examples/network_service_tiers/main.tf, examples/network_service_tiers/outputs.tf, examples/network_service_tiers/variables.tf, examples/network_service_tiers/versions.tf
Purpose is to add Terraform tab to
https://cloud.google.com/network-tiers/docs/using-network-service-tiers#setting_the_tier_for_all_resources_in_a_project
=> chore: adding command to set Network Service Tier for a project

examples/basic_secondary_ranges/README.md, examples/basic_secondary_ranges/main.tf, examples/basic_secondary_ranges/outputs.tf, examples/basic_secondary_ranges/variables.tf, examples/basic_secondary_ranges/versions.tf
Intending to use this here:
https://cloud.devsite.corp.google.com/vpc/docs/configure-alias-ip-ranges#creating_a_subnet_with_one_or_more_secondary_cidr_ranges
=> Added new example for a subnet with a secondary range

README.md, outputs.tf
Just adds every `subnet_id` as an output. Useful for use with other modules that requires a list of the subnet ids.
=> Adds `subnet_ids` as an output

examples/private_service_connect_google_apis/main.tf
Used on this page:
https://cloud.google.com/vpc/docs/configure-private-service-connect-apis
=> Changed START to END for closing region tag

modules/fabric-net-svpc-access/main.tf
Replaced `count` with `for_each` on `google_compute_subnetwork_iam_binding` to prevent destroy/recreate when the list changes. 
My institution uses the same codebase from Google CFT, and I did the same refactoring on our end to minimize unnecessary drifts when list changes... so, just contributing this fix back to your codebase if deemed worthy. Thank you.
=> fix: Refactored IAM binding for network users

README.md, modules/vpc/README.md, modules/vpc/outputs.tf, outputs.tf
Fixes issue #307
As per the above issue, this PR adds a `network_id` output to the root module and the `vpc` module.
This is my first contribution to this project, do let me know if I have missed something; will be happy to modify the PR accordingly!
=> Adding Network ID as a top level module output

modules/vpc-serverless-connector-beta/README.md, modules/vpc-serverless-connector-beta/main.tf
Expose the max_throughput argument of the google_vpc_access_connector.
=> Add max_throughput to vpc-serverless-connector-beta

examples/multi_vpc/main.tf, examples/secondary_ranges/main.tf, examples/simple_project/main.tf, examples/simple_project/versions.tf, modules/subnets/main.tf
Closes: https://github.com/terraform-google-modules/terraform-google-network/pull/340
in v4 https://github.com/hashicorp/terraform-provider-google/pull/10429, beta clients got stripped from ga provider and the following diffs started appearing when the ga provider was using beta endpoints.﻿
```
Terraform will perform the following actions:
~ resource "google_compute_subnetwork" "subnetwork" {
id                         = "projects/REDACTED/regions/europe-west1/subnetworks/proxy-only-subnet"
name                       = "proxy-only-subnet"
- role                       = "ACTIVE" -> null
}
```
@bharathkkb
=> Promote role and purpose of subnet to GA

.gitignore, examples/simple_project/main.tf, modules/subnets/README.md, modules/subnets/main.tf, test/integration/simple_project/simple_project_test.go
This change added filter_expr control for log_config inside subnets module to address the following issue:
https://github.com/terraform-google-modules/terraform-google-network/issues/353
Changed simple_project test to set a non-default value to filter_expr, updated documentation manually and updated integration test to reflect new non-default value
=> feat: add filter_expr control in subnet log_config

modules/private-service-connect/README.md
`terraform init` was failing when using the source from the README.
=> Fix README.md typo

modules/subnets-beta/README.md, modules/subnets-beta/main.tf, modules/subnets/README.md
As mentioned in #407 I just aligned the two module definition and READMEs, as there are virtually the same as of now and will only be be kept for potential future beta features and backwards compatibility as requested by you @bharathkkb.
=> fix: align subnet modules

helpers/migrate.py
Not sure if anyone might find this useful, but I ran into an issue where my state resource has the "attributes" key defined, but not "attributes_flat".  Recently updated this project tf version to `0.12`, state version appears as `4`. I'm thinking that this might just be an artifact of having really old state. At any rate, this little modification allows the script to run on my archaic state and provide migration instructions without affecting original functionality.
=> fix: Adds support for pulling "attributes" as well as "attributes_flat" from pulled state.

modules/network-firewall-policy/README.md
Noticed the readme links pointing to the wrong repo
=> chor: Fix network-firewall-policy readme links

README.md, codelabs/simple/README.md, examples/submodule_svpc_access/README.md, metadata.yaml, modules/subnets-beta/README.md, modules/subnets-beta/main.tf, modules/subnets-beta/metadata.yaml, modules/subnets-beta/variables.tf, modules/subnets/README.md, modules/subnets/main.tf, modules/subnets/metadata.yaml, modules/subnets/variables.tf, test/setup/README.md, variables.tf
- Add `metadata_fields` to the `log_config` block of subnets submodule
- Update documentation
- Terraform resource: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_subnetwork.html#metadata_fields
- Ref #239
Note:
- Had to change `subnets` variable type from `list(map(string))` to `list(object{...})`, to allow heterogeneous types.
=> feat: add metadata_fields support

modules/subnets-beta/README.md, modules/subnets-beta/main.tf, modules/subnets/README.md, modules/vpc/README.md, modules/vpc/main.tf, modules/vpc/variables.tf
* Add support for ULA on VPC network
* Add optional ULA prefix for VPC network
* Add documentation for subnet `stack` to enable dual-stack networking
* Add documentation for IPv6 type to enable either `EXTERNAL` v6 addressing or `INTERNAL` when ULA is enabled in the VPC
=> feat: Add IPv6 ULA support and document subnet ipv6 support

modules/network-peering/README.md, modules/network-peering/main.tf, modules/network-peering/variables.tf, modules/network-peering/versions.tf
Add `stack_type` variable to the `network-peering` module.
The `stack_type` value will be added to `local` and `peer` resources.
[Link](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_network_peering#stack_type) to the `stack_type` field in google provider.
=> feat: add stack type to peering module

docs/upgrading_to_v10.0.0.md, modules/private-service-connect/README.md, modules/private-service-connect/main.tf, modules/private-service-connect/variables.tf, modules/private-service-connect/versions.tf
Hi, I would propose to add optional variable of `project_region` for this module.
The idea is to allow specifying custom, not in us-central1, namespace link.
=> feat: Add service_directory_registrations: namespace and service_directory_region

modules/private-service-connect/README.md, modules/private-service-connect/main.tf, modules/private-service-connect/variables.tf
Adds the ability to allow specifying the PSC endpoint as global or not. See https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_forwarding_rule#allow_psc_global_access
=> feat: allow enabling global access for PSC endpoints

README.md, docs/upgrading_to_v10.0.0.md, main.tf, modules/vpc/README.md, modules/vpc/main.tf, modules/vpc/variables.tf, modules/vpc/versions.tf, variables.tf
This PR adds the `network_profile` setting to the `google_compute_network` resource and to the top level module.  This change is necessary to enable the RDMA profiles, required for the new GPU machine types on GCP.
This is currently untested and will be updated once the `google-beta` provider with these changes has been released (expected 11/25/24).
=> feat!: Add network_profile setting to network, update network resource provider

modules/vpc-serverless-connector-beta/README.md
As per the [latest documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/vpc_access_connector):
> Only one of max_throughput and max_instances can be specified. The use of max_throughput is discouraged in favor of max_instances. 
If you are using both, you will get this error: 
```
╷
│ Error: Conflicting configuration arguments
│ 
│   with module.serverless_connector.google_vpc_access_connector.connector_beta["ew4-serverless"],
│   on .terraform/modules/serverless_connector/modules/vpc-serverless-connector-beta/main.tf line 36, in resource "google_vpc_access_connector" "connector_beta":
│   36:   max_instances  = each.value.max_instances
│ 
│ "max_instances": conflicts with max_throughput
╵
╷
│ Error: Conflicting configuration arguments
│ 
│   with …
```
=> chore: Update README.md

README.md, modules/vpc/README.md, modules/vpc/variables.tf, variables.tf
The docs say that the default is `STANDARD` but it is `LEGACY`.
Fixup of #616, which changed the default value but missed some of the docs
=> fix(docs): Correct bgp_best_path_selection_mode default value

test/integration/network_connectivity_center/network_connectivity_center_test.go
It is taking long time for GCP APIs to get updated  spokeSummary which is causing tests to fail. Removing spoke count from the NCC test.
=> chore: fixed tests

Makefile, docs/upgrading_to_v12.0.0.md, examples/network_connectivity_center/main.tf, examples/network_connectivity_center/versions.tf, metadata.yaml, modules/fabric-net-firewall/metadata.yaml, modules/fabric-net-svpc-access/metadata.yaml, modules/firewall-rules/metadata.yaml, modules/hierarchical-firewall-policy/metadata.yaml, modules/network-connectivity-center/README.md, modules/network-connectivity-center/main.tf, modules/network-connectivity-center/metadata.yaml, modules/network-connectivity-center/outputs.tf, modules/network-connectivity-center/variables.tf, modules/network-firewall-policy/metadata.yaml, modules/network-peering/metadata.yaml, modules/private-service-connect/metadata.yaml, modules/routes-beta/metadata.yaml, modules/routes/metadata.yaml, modules/subnets-beta/metadata.yaml, modules/subnets/metadata.yaml, modules/vpc-serverless-connector-beta/metadata.yaml, modules/vpc/metadata.yaml, test/setup/main.tf
=> feat: added producer VPC network spoke
