terraform-google-modules/terraform-google-network

examples/multi_vpc/main.tf
examples/simple_project/main.tf

Formatted examples using `terraform fmt`.

Format examples

---

test/integration/gcloud-test/launch.sh

Launch.sh script used for tests

delete dup command on sh

---

codelabs/simple/main.tf

Published lab: https://codelabs.developers.google.com/codelabs/hashicorp-terraform-networking
Source doc: https://docs.google.com/document/d/1HlV8ZHgYh2vGUjQyM5AHg_U0FhDdRnBAws_PZA4JFwY/edit

Add simple codelab

---

CHANGELOG.md

This branch adjusts the CHANGELOG to match https://keepachangelog.com/ and adds the features of 0.6.0.

Add 0.6.0 to CHANGELOG

---

README.md

Per https://github.com/terraform-google-modules/terraform-google-network/pull/47#discussion_r300795317

Update README example to version-pin to patch version

---

README.md
main.tf
variables.tf

Signed-off-by: Ken Evensen <kdevensen@google.com>
Fixes #56

Added description and auto_create_subnetworks variables.

---

CHANGELOG.md
examples/submodule_svpc_access/main.tf
examples/submodule_svpc_access/terraform.tfvars
examples/submodule_svpc_access/variables.tf
modules/fabric-net-svpc-access/README.md
modules/fabric-net-svpc-access/main.tf
modules/fabric-net-svpc-access/variables.tf

* add management of host service agent role for GKE use cases
* improve documentation
* example fixes

Shared VPC access submodule improvements

---

CHANGELOG.md
README.md
examples/submodule_svpc_access/README.md
main.tf
modules/fabric-net-svpc-access/README.md

* Fix #63
* Fixed default values for `Subnet Inputs` in README.md

Set default value for `next_hop_internet` variable

---

CHANGELOG.md

Hopefully I got the Changelog right this time.

Update Changelog for 1.4.0 release

---

main.tf

Reverts terraform-google-modules/terraform-google-network#81
Fixes https://github.com/terraform-google-modules/terraform-google-network/issues/92

Revert "Add depends_on to created_subnets data fetch"

---

modules/fabric-net-svpc-access/README.md

Fix module source in README example

---

docs/upgrading_to_v2.0.md

Add output notes to upgrade guide

---

README.md
variables.tf

Fixes #156 by removing `create_network` variable

Bugfix: remove create network

---

modules/network-peering/main.tf

Remove quoted references

---

CHANGELOG.md
modules/routes-beta/README.md
modules/routes/README.md

chore: Correct documentation around delete_default_internet_gateway_routes from example..

---

modules/subnets-beta/versions.tf

fix: Add support for 3.x provider to beta subnets module

---

examples/delete_default_gateway_routes/versions.tf
examples/ilb_routing/versions.tf
examples/multi_vpc/versions.tf
examples/secondary_ranges/versions.tf
examples/simple_project/versions.tf
examples/simple_project_with_regional_network/versions.tf
examples/submodule_firewall/versions.tf
examples/submodule_network_peering/versions.tf
examples/submodule_svpc_access/versions.tf
modules/fabric-net-firewall/versions.tf
modules/fabric-net-svpc-access/versions.tf
modules/network-peering/versions.tf
modules/routes-beta/versions.tf
modules/routes/versions.tf
modules/subnets-beta/versions.tf
modules/subnets/versions.tf
modules/vpc/versions.tf
test/setup/versions.tf
versions.tf

Referencing other Google modules like
https://github.com/terraform-google-modules/terraform-google-project-factory/pull/505
Signed-off-by: Yong Wen Chua <lawliet89@users.noreply.github.com>

chore: Remove < 0.14 constraint

---

modules/routes/README.md
modules/routes/main.tf

fixes https://github.com/terraform-google-modules/terraform-google-network/issues/240

feat: add next_hop_ilb to routes module

---

modules/firewall-rules/README.md

updated rules in readme example to resolve issue #252

---

examples/simple_project/main.tf

This will be used to update this Terraform example:
https://cloud.google.com/vpc/docs/using-vpc#create-custom-network

Prepare sample for inclusion in cloud docs

---

examples/basic_auto_mode/README.md
examples/basic_auto_mode/main.tf
examples/basic_auto_mode/outputs.tf
examples/basic_auto_mode/variables.tf
examples/basic_auto_mode/versions.tf
examples/basic_custom_mode/README.md
examples/basic_custom_mode/main.tf
examples/basic_custom_mode/outputs.tf
examples/basic_custom_mode/variables.tf
examples/basic_custom_mode/versions.tf

Added two basic VPC examples: auto mode and custom mode

---

test/integration/simple_project/controls/gcloud.rb
test/integration/simple_project/controls/gcp.rb

These are already tested via gcloud.

chore: Remove redundant subnet tests

---

modules/fabric-net-svpc-access/main.tf
modules/fabric-net-svpc-access/versions.tf
modules/vpc/main.tf
modules/vpc/versions.tf

fixes #268 similar to https://github.com/terraform-google-modules/terraform-google-project-factory/pull/560

fix: switch shared_vpc resources to beta provider

---

examples/basic_shared_vpc/main.tf

For this section:
https://cloud.google.com/vpc/docs/provisioning-shared-vpc#creating_an_instance_template_in_the_shared_vpc_network
Also fixed IP address reference

Added snippet for instance template

---

examples/basic_shared_vpc/main.tf

Noticed that 10.0.0.1 is assigned to the gateway

Changed IP address to .8 because .1 is usually the gateway address

---

examples/private_service_connect_google_apis/README.md
examples/private_service_connect_google_apis/main.tf
examples/private_service_connect_google_apis/outputs.tf
examples/private_service_connect_google_apis/variables.tf
examples/private_service_connect_google_apis/versions.tf

Planning to use here:
https://cloud.devsite.corp.google.com/vpc/docs/configure-private-service-connect-apis

Added example for private service connect for google APIs

---

.gitignore
.kitchen.yml
build/int.cloudbuild.yaml
examples/submodule_vpc_serverless_connector/README.md
examples/submodule_vpc_serverless_connector/main.tf
examples/submodule_vpc_serverless_connector/outputs.tf
examples/submodule_vpc_serverless_connector/variables.tf
examples/submodule_vpc_serverless_connector/versions.tf
modules/firewall-rules/README.md
modules/vpc-serverless-connector-beta/README.md
modules/vpc-serverless-connector-beta/main.tf
modules/vpc-serverless-connector-beta/outputs.tf
modules/vpc-serverless-connector-beta/variables.tf
modules/vpc-serverless-connector-beta/versions.tf
test/fixtures/submodule_vpc_serverless_connector_beta/main.tf
test/fixtures/submodule_vpc_serverless_connector_beta/outputs.tf
test/fixtures/submodule_vpc_serverless_connector_beta/variables.tf
test/integration/submodule_vpc_serverless_connector_beta/controls/gcloud.rb
test/integration/submodule_vpc_serverless_connector_beta/controls/inspec_attributes.rb
test/integration/submodule_vpc_serverless_connector_beta/inspec.yml
test/setup/iam.tf
test/setup/main.tf

Adding vpc-serverless-connector-submodule-beta

---

examples/packet_mirroring/README.md
examples/packet_mirroring/main.tf
examples/packet_mirroring/outputs.tf
examples/packet_mirroring/variables.tf
examples/packet_mirroring/versions.tf

Intending to use this snippet here:
https://cloud.google.com/vpc/docs/using-packet-mirroring#creating

Added packet mirroring Terraform example

---

examples/submodule_vpc_serverless_connector/README.md
examples/submodule_vpc_serverless_connector/main.tf
examples/submodule_vpc_serverless_connector/outputs.tf

Intending to use on this page:
https://cloud.google.com/vpc/docs/configure-serverless-vpc-access

Prepared submodule_vpc_serverless_connector example for inclusion in VPC docs

---

examples/submodule_vpc_serverless_connector/main.tf

Intending to use in this section:
https://cloud.google.com/vpc/docs/configure-serverless-vpc-access#creating_a_connector

Added resource to enable the necessary API

---

examples/basic_shared_vpc/README.md
examples/basic_shared_vpc/main.tf

Intending to add this example here:
https://cloud.devsite.corp.google.com/vpc/docs/provisioning-shared-vpc#creating_an_internal_load_balancer_forwarding_rule

Added Shared VPC forwarding rule example

---

build/int.cloudbuild.yaml
examples/global-network-firewall-policy/main.tf
examples/regional-network-firewall-policy/main.tf
modules/network-firewall-policy/README.md
modules/network-firewall-policy/main.tf

fix: network attachment error in firewall policy sub-module

---

modules/firewall-rules/README.md
modules/firewall-rules/outputs.tf

Fixes missing outputs when using ingress/egress rules

fix(firewall-rules): Update firewall-rules outputs

---

examples/private_service_connect_google_apis/main.tf
examples/private_service_connect_google_apis/versions.tf

Removed provider from main.tf and changed the provider name from google-beta to google in versions.tf

chore(examples): changed provider from google-beta to google

---

modules/network-connectivity-center/main.tf

- Remove artificial depencency for serial Spoke attachment as internal dependency is fixed
- Move VPC Spoke creation to the spoke project

NCC: Spoke creation in spoke project, remove artificial dependency
